<div class="tag-list">
	<ul>
		<li class="tag" data-value="Brand Building / Product Education" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Brand Building / Product Education"><i class="fa fa-circle tag-red"></i><span class="tag-title">Brand Building / Product Education</span></li>
		<li class="tag" data-value="Marketing" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Marketing"><i class="fa fa-circle tag-pink"></i><span class="tag-title">Marketing</span></li>
		<li class="tag" data-value="Orange Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Orange Tag"><i class="fa fa-circle tag-orange"></i><span class="tag-title">Orange Tag</span></li>
		<li class="tag" data-value="E-Commerce" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="E-Commerce"><i class="fa fa-circle tag-yellow"></i><span class="tag-title">E-Commerce</span></li>
		<li class="tag" data-value="Retail Support" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Retail Support"><i class="fa fa-circle tag-green"></i><span class="tag-title">Retail Support</span></li>
		<li class="tag" data-value="Dark Green Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Dark Green Tag"><i class="fa fa-circle tag-green-dark"></i><span class="tag-title">Dark Green Tag</span></li>
		<li class="tag" data-value="Blue Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Blue Tag"><i class="fa fa-circle tag-blue"></i><span class="tag-title">Blue Tag</span></li>
		<li class="tag" data-value="Dark Blue Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Dark Blue Tag"><i class="fa fa-circle tag-blue-dark"></i><span class="tag-title">Dark Blue Tag</span></li>
		<li class="tag" data-value="Lorem Ipsum Dolor" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Lorem Ipsum Dolor"><i class="fa fa-circle tag-purple-dark"></i><span class="tag-title">Lorem Ipsum Dolor</span></li>
		<li class="tag" data-value="Purple Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Purple Tag"><i class="fa fa-circle tag-purple"></i><span class="tag-title">Purple Tag</span></li>
		<li class="tag" data-value="Onsectetur Adipiscing" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Onsectetur Adipiscing"><i class="fa fa-circle tag-brown"></i><span class="tag-title">Onsectetur Adipiscing</span></li>
		<li class="tag" data-value="Tan Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Tan Tag"><i class="fa fa-circle tag-tan"></i><span class="tag-title">Tan Tag</span></li>
		<li class="tag" data-value="Gray Tag" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Gray Tag"><i class="fa fa-circle tag-gray"></i><span class="tag-title">Gray Tag</span></li>
		<li class="tag" data-value="Custom Tag Color" data-group="post-tag"><input type="checkbox" class="hidden-xs-up" name="post-tag" value="Custom Tag Color"><i class="fa fa-circle tag-custom" style="color: #74DEF4; border-color: #74DEF4"></i><span class="tag-title">Custom Tag Color</span></li>
	</ul>
</div>